### ISSUE TITLE
Fix your textures.

### ISSUE THREAD

**Issue by MagmaSlime123** [facetorched/tfc-plus-aesthetics#2]
If this is no longer being worked on, give it to someone else, or remove it.

![2022-12-29_11 12 20](https://user-images.githubusercontent.com/51277766/209992945-e0047324-4902-451a-8a65-29422897904f.png)

**Comment by facetorched** [comment]
I'm not sure what you mean by "give it to someone else or remove it". I will continue to fix bugs but at this time there are no features planned for this mod.

Can you please elaborate about what is actually wrong? Do you mean the "snow" textures for the lilypad-like plants? We didn't bother making those textures since you can't see them below the rendered snow layer. 

Do you think we should:

- Hide these in the creative menu?

- copy the winter texture?

- show the snow texture in place of the item?

**Comment by MagmaSlime123** [comment]
Sorry about that. You could probably do 1 of these 3.

**Comment by facetorched** [comment]
Resolved in 1d2ac89924cdc4e80fecbbf2bc74ac7142118805
